services:
    web:
        image: nginx:latest
        ports:
            - "8020:80"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./app:/app
        depends_on:
            - php
        restart: always

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        restart: always
